### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by longpt214** [aonotas/deep-crf#55]
Hello,

I have the following issue. I have looked through all existing issues and it seems that it is a new issue. It happens when I try to train a model. The errors happen for both dummy data (I got on your README, and the delimiter is one space character) and my data. Could you give me insights into where the problem is?

```
deep-crf train dummy_training.txt --delimiter=' ' --dev_file input_file_dev.txt --save_dir . --save_name bilstm-cnn-crf_adam --optimizer adam
```

```
[2017-12-31 08:05:23,945] [INFO] start training... (run@main.py:417)
[2017-12-31 08:05:23,945] [INFO] epoch:0 (run@main.py:424)
[2017-12-31 08:05:23,945] [INFO]  [train] (run@main.py:425)
[2017-12-31 08:05:24,165] [INFO]   loss     :8.92536354065 (run@main.py:462)
[2017-12-31 08:05:24,165] [INFO]   accuracy :23.076923076923077 (run@main.py:463)
Traceback (most recent call last):
  File "/Users/longpham/anaconda/bin/deep-crf", line 11, in <module>
    load_entry_point('DeepCRF==1.0', 'console_scripts', 'deep-crf')()
  File "/Users/longpham/anaconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/longpham/anaconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/longpham/anaconda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/longpham/anaconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/longpham/anaconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/longpham/anaconda/lib/python3.6/site-packages/DeepCRF-1.0-py3.6.egg/deepcrf/__init__.py", line 66, in train
  File "/Users/longpham/anaconda/lib/python3.6/site-packages/DeepCRF-1.0-py3.6.egg/deepcrf/main.py", line 467, in run
  File "/Users/longpham/anaconda/lib/python3.6/site-packages/DeepCRF-1.0-py3.6.egg/deepcrf/main.py", line 369, in eval_loop
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by longpt214** [comment]
Never mind! The problem is because I used the wrong format for dev_file. The format should be similar to training file.
